
name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: java version
        run: java -version
      - name: java version
        run: mvn --version
      - name: python version
        run: python --version
      - name: docker version
        run: docker -v
